### ISSUE TITLE
mapRej

### ISSUE THREAD

**Issue by char0n** [char0n/monadT#10]
mapRej doesn't work as expected. Needs logical fix.

**Comment by char0n** [comment]
@michaelkuk I suspect this this is just a manifestation of bigger problem. Our laws of natural transformation between Future and Either may not be correct.

Example of incorrect natural transformation laws: 
https://github.com/char0n/monad-t/blob/master/test/FlutureTMonetEither/index.js#L442

For example we expect that rejected run (Future) wraps error directly and not Either.Left.


Things to study: 
http://justinhj.github.io/2017/06/02/future-either-and-monad-transformers.html
https://github.com/scala-hamsters/hamsters/blob/master/shared/src/main/scala/io/github/hamsters/MonadTransformers.scala

**Comment by char0n** [comment]
Ok I gave this a lot of thoughts and studied the scalaz and hamster implementation of FutureTEither transformers. The way we have this implemented is surprisingly correct ;] Laws of natural transformations applies correctly. `run` of type `Future` either contains rejected `Error` or resolved `Either`.

**Comment by char0n** [comment]
@michaelkuk going through the hamster source code I noticed that they have `filter` and [`filterWithDefault`](https://github.com/scala-hamsters/hamsters/blob/master/shared/src/main/scala/io/github/hamsters/MonadTransformers.scala#L106). I propose to use this naming too, to get rid of confusion with `filter` seconds param.

```javascript
FutureTEither
  .fromValue(1)
  .filter(eq(2)); //=> FutureTEither<Future<Either.Left('No value matching predicate')>>

FutureTEither
  .fromValue(1)
  .filterWithDefault(eq(2), Error('Doesn't equal 2')); //=> FutureTEither<Future<Either.Left(Error('Doesn't equal 2'))>>
```
What do you think. We can create a separate issue for it, if agreed upon.

**Comment by michaelkuk** [comment]
@char0n point of the issue is to introduce a way to somehow transform `Either.Left` value in the pipeline. Currently there is mechanism that would allow it prior to `fork`. More important is the fact that if one is forking using the `.promise()` method and wants to transform error contained in `Either.Left` this operation has to be implementing using `catch()` method on the promise API from which a new rejected promise has to be returned.

**Comment by michaelkuk** [comment]
@char0n I would also try to avoid breaking API change of the `filter` operator it is currently being used in some codebases. On the other hand it makes sense to provide default value for use cases where no explicit data structure is required. I would therefore propose to keep the current api of filter method as is but to provide default value to the second argument.

**Comment by char0n** [comment]
I would go for a [leftMap](https://github.com/monet/monet.js/blob/develop/src/monet.js#L924). The name is not consistent with the `mapRej` in the sense that the order of the words is reversed (first is `map`, then `Rej`). But anyway I would keep the same operator names from the original libraries. That why this FutureTEither type is specific to fluture and monet respectively.



```javascript
FutureTEither
  .of(Future.of(Either.Left(1)))
  .leftMap(e => e + 1)
  .fork(console.error, console.dir); //=> console.error(2)
```

`leftMap` is ignored when Future is rejected or Either is Right side.

**Comment by char0n** [comment]
`leftMap` continues in #12. Closing this one.
