### ISSUE TITLE
Better logical filter

### ISSUE THREAD

**Issue by char0n** [char0n/monadT#11]
@michaelkuk going through the hamster source code I noticed that they have filter and filterWithDefault. I propose to use this naming too, to get rid of confusion with filter seconds param.

```javascript
FutureTEither
  .fromValue(1)
  .filter(eq(2)); //=> FutureTEither<Future<Either.Left('No value matching predicate')>>

FutureTEither
  .fromValue(1)
  .filterWithDefault(eq(2), Error('Doesn't equal 2')); //=> FutureTEither<Future<Either.Left(Error('Doesn't equal 2'))>>

FutureTEither
  .fromValue(1)
  .filterWithDefault(eq(2), val => Error(`${val} doesn't equal 2`)); //=> FutureTEither<Future<Ei

**Comment by michaelkuk** [comment]
@char0n I would also try to avoid breaking API change of the `filter` operator it is currently being used in some codebases. On the other hand it makes sense to provide default value for use cases where no explicit data structure is required. I would therefore propose to keep the current api of filter method as is but to provide default value to the second argument.

**Comment by char0n** [comment]
Yes of course it is being used and of course it would require some work refactoring on library consumer part ;] But forget about that and just think if the API I am proposing make more sense than the API we currently have now. We will mark usage of `filter` with second argument as deprecated and will keep backward compatibility for some time and introduce this new `filterWithDefault` which is more declarative in nature.  After some reasonable amount of time we will remove the second argument from the `filter` method.

**Comment by michaelkuk** [comment]
@char0n well I still do not understand why to introduce two operators, when the same feat can be achieved with the original one. I think this approach chooses academic correctness over usage convenience, which would not be my first choice.

**Comment by char0n** [comment]
You know me, I like academical correctness ;] But the problem is not purely academical but also practical. This method breaks single responsibility principle and is not declarative enough to quickly understand what it does and how to use it. Remember when you first saw it ? ;]

Regarding SRP (single responsibility principle):
`filter` - does one thing and one thing only, it filters the value locked inside the container with predicate
`filterWithDefault` - does one thing and one thing only, filters the value and assigns the default is predicate fails. It does exactly what it says it does

I guess that's my whole reasoning. ScalaZ and Hamster seems to share my opinion on this matter by implementing it in the same way I'm describing.

**Comment by char0n** [comment]
Gave it another thoughts and decided that `filter` without additional default doesn't make sense because you won't know when and why the transformer rejected during the forking. It could introduce bad code practices and code smell. Still leaving opened option for introducing alias `filterWithDefault` for `filter` method, but leaving it for the uncertain future ;]
